spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:postgresql://localhost:3005/nexus_identity
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

management:
  endpoint:
    web:
      exposure:
        include: health,info
logging:
  level:
    root: INFO

jwt:
  secret: 8v4aF7mY2sLkP9zQx1rN6uW3cH8jT5eV9bK2mD7pR4yX6nL1qS0fG3hJ8tY5uC2
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000


